version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: strapi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hadiazb
      MYSQL_DATABASE: strapi
      MYSQL_USER: hadiazb
      MYSQL_PASSWORD: hadiazb
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
